title: Carmine Paolino
description: >- # this means to ignore newlines until "baseurl:"
  Machine Learning, Deep Learning, Recommender Systems, Productivity
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://paolino.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: paolino
github_username:  crmne

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
